pipeline {
    agent any

    stages {
        stage('JenkinsExample') {
            stages {
                stage('JenkinsExample - Build Image and Deploy') {
                    steps {
                        sh("docker build -t dotnet-jenkins-example:latest -f DevOps/Docker/Dockerfile .")
                    }
                }
            }
        }

       	stage('Clear Produced Dangling Containers/Layers') {
            steps {
				sh("docker images | grep '<none>' | awk '{print \$3}' | xargs -I {} docker rmi -f {} || true")
				sh("docker images | grep 'registry.toprak.tkholding.com' | awk '{print \$3}' | xargs -I {} docker rmi -f {} || true")
            }
        }
    }
}